### ISSUE TITLE
@nhp not respecting timeout?

### ISSUE THREAD

**Issue by sinneduy** [hashicorp/vault-ruby#123] opened 2016-12-16 23:12 UTC
Hey guys, we're seeing something weird where it looks like `read_timeout` is not being respected

We're utilizing the block style of configuration like so:

```
2.2.5 : > Vault.configure do |config|
2.2.5 : >     config.timeout = 5
2.2.5 :?>   config.ssl_timeout = 5
2.2.5 :?>   config.open_timeout = 5
2.2.5 :?>   config.read_timeout = 5
2.2.5 :?>   config.address = "https://127.0.0.1:8200"
2.2.5 :?>   end
 => "https://127.0.0.1:8200"
```

However, it looks like the `Net:HTTP:Peristent` isn't seeing the timeout in *its* configuration
```
2.2.5 : > Vault.client.instance_variable_get(:@read_timeout)
 => 5
2.2.5 : > Vault.client.instance_variable_get(:@nhp).instance_variable_get(:@read_timeout)
 => nil
```

I don't see where this might have been [lost](https://github.com/hashicorp/vault-ruby/blob/347589d7ecad480827856115bcf613d38a42744a/lib/vault/client.rb#L100-L102), but I may not have a good enough understanding of the client - can you advise?

**Comment by sinneduy** [comment] 2016-12-16 23:16
However, it looks like it works if you use the inline configuration, so it seems like this may be a block configuration issue: 

```
2.2.5 > client_1 = Vault::Client.new(address: "https://127.0.0.1:8200", read_timeout: 5, open_timeout: 5, ssl_timeout:5, timeout: 5)
2.2.5 > client_1.instance_variable_get(:@nhp).instance_variable_get(:@read_timeout)
 => 5
```

**Comment by sethvargo** [comment] 2017-01-17 18:45
This looks like a duplicate of #108. There seems to be something lost, but I haven't been able to trace it down 😦

**Closed by sethvargo** 2017-01-17 18:45 UTC

**Comment by sinneduy** [comment] 2017-01-17 18:53
except that's also closed...?

So is this not an issue to you guys?

Perhaps you should remove the block configuration from your documentation in the meantime?

**Comment by sethvargo** [comment] 2017-01-17 19:16
@sinneduy #108 is not closed - it's open and labeled a bug. Could you share where you are seeing it is closed?

**Comment by sinneduy** [comment] 2017-01-17 19:22
Apologies, I misread.  Still, it would be helpful to not have that configuration style in the documentation if we aren't aware of a fix anytime in the near future

**Comment by evanphx** [comment] 2017-01-17 20:44
@sinneduy Are you having this issue with the latest release?

**Comment by sinneduy** [comment] 2017-01-25 01:57
yes.

```
# gem install vault
Successfully installed vault-0.7.3
Parsing documentation for vault-0.7.3
Installing ri documentation for vault-0.7.3
Done installing documentation for vault after 1 seconds
1 gem installed
# rails c

2.2.5 :001 > Vault.configure do |config|
2.2.5 :002 >     config.timeout = 5
2.2.5 :003?>   config.ssl_timeout = 5
2.2.5 :004?>   config.open_timeout = 5
2.2.5 :005?>   config.read_timeout = 5
2.2.5 :006?>   config.address = "https://127.0.0.1:8200"
2.2.5 :007?>   end
 => "https://127.0.0.1:8200"
2.2.5 :008 > Vault.client.instance_variable_get(:@read_timeout)
 => 5
2.2.5 :009 > Vault.client.instance_variable_get(:@nhp).instance_variable_get(:@read_timeout)
 => nil
```
